# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.5"
install: pip install -r requirements/ci.txt
env:
  - DJANGO_SETTINGS_MODULE='syracuse_bizport.settings.ci'
addons:
  postgresql: "9.4"
before_script: python ./manage.py collectstatic --noinput
script:
  - pep8
  - python ./manage.py test
notifications:
    slack: cfa:0TrBnxh9hLyVfs2jxUHrMvW2
